### ISSUE TITLE
Mapping issue

### ISSUE THREAD

**Issue by Ginsterrr** [byutrg/Csh-MultiTerm-TBX-Converter#1] opened 2019-12-27 11:08 UTC
When generating a map for termbases, the user is prompted to add TBX Data categories. In my case the convertor seems to have an issue with the category "definition" (screenshot 1). Although it seems to be a standard category (screenshot 2), I'm forced to choose a category from the list (screenshot 3), otherwise the program would just close without error message (I can't find any logs either). Once added, I need to map individually every entry (screenshot 4). I suppose that's not the intended way to proceed, but I can't find any instructions on how to process otherwise.
<img width="593" alt="1" src="https://user-images.githubusercontent.com/59112670/71515039-9b62a380-28a1-11ea-9486-d53fc2bccb28.PNG">
<img width="451" alt="2" src="https://user-images.githubusercontent.com/59112670/71515040-9b62a380-28a1-11ea-8aef-5bdc45cf649a.PNG">
<img width="607" alt="3" src="https://user-images.githubusercontent.com/59112670/71515041-9bfb3a00-28a1-11ea-97e5-4b57d9cab623.PNG">
<img width="599" alt="4" src="https://user-images.githubusercontent.com/59112670/71515042-9bfb3a00-28a1-11ea-8134-0783325aac76.PNG">

**Comment by byutrg** [comment] 2022-09-04 03:20
This looks to have been caused by adding a second "definition" to the list of mapped data categories. From Image 1 you can see that "definition" has already been added to the list automatically.  Adding a second "definition" to the list causes the tool to ask which of the two "definition" data categories your fields belong to.

There was a line of code that was intended to prevent this, but it was not functioning properly. It has been fixed in the latest release.

Fixed in https://github.com/byutrg/Csh-MultiTerm-TBX-Converter/commit/92a8813b7fcdb11e0de659e65e8e1771b9e46b97

**Closed as completed by byutrg** 2022-09-04 03:20 UTC
Labels: bug
